[pytest]
# You can customize pytest's options with an env variable:
#
# PYTEST_ADDOPTS="-vv --showlocals"
#
# Precidence is: pytest.ini addopts → PYTEST_ADDOPTS → command-line arguments
#
# -rw: summarize warnings at end of test
# -re: ditto for errors
# -rf: ditto for failed
addopts = --tb native -rw -re -rf
testpaths = tests
filterwarnings =
    # Treat any warning issued in a test as an exception so we are forced to explicitly handle or
    # ignore it.
    error

    # REMINDER: when adding an ignore, add an issue to track it
    #----------------------------------------------------------

    # Example follows
    #ignore:'cgi' is deprecated and slated for removal in Python 3\.13:DeprecationWarning:webob\.compat
