#!/usr/bin/env bash
# mise description="Bootstrap project"
#
# Originates from https://github.com/level12/copier-py-package
#
# Consider updating the source file in that repo with enhancements or bug fixes needed.

echo 'VIRTUAL_ENV:' $VIRTUAL_ENV
echo 'PATH:' $PATH
git init
reqs config
reqs bootstrap
reqs sync --force
pre-commit install
pre-commit autoupdate
git add .
git commit -m 'initial commit after copier-py-package generation'
